version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-s3: circleci/aws-s3@4.0.0
jobs:
  build_plugin:
    docker:
      - image: cimg/base:current
    steps:
    - checkout
    # Install nvm
    - run:
        name: Install nvm and build
        command: |
          set +e
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install
          npm install -g yarn@latest
          yarn kbn bootstrap
          cd plugins
          git clone git@github.com:CST-Dev-Analytics/nia-case-enrichment-kibana-plugin.git
          cd nia-case-enrichment-kibana-plugin
          git checkout develop
          yarn install
          #yarn kbn bootstrap
          yarn plugin-helpers build  
          ls build/caseEnrichment-8.2.4.zip
          # tranfer the file to cstproj use release https://github.com/CST-Dev-Analytics/cst_proj/tree/main/kibana/plugins
    - save_cache:
        paths: [plugins/nia-case-enrichment-kibana-plugin/build]
        key: kibana-plugins-build
    
  push_plugin_image:
    docker:
       - image: cimg/aws:2023.12
    steps:
      - restore_cache:
          keys: [kibana-plugins-build]
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: s3:/cst-custom-plugins/prefix
      - aws-s3/copy:
          from: plugins/nia-case-enrichment-kibana-plugin/build/caseEnrichment-8.2.4.zip
          to: s3://cst-custom-plugins


  install_and_build:
    docker:
      - image: cimg/base:current
    steps:
    - checkout
    # Install nvm
    - run:
        name: Install nvm and build
        command: |
          set +e
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install
          npm install -g yarn@latest
          yarn kbn bootstrap
          yarn build --docker-images --skip-os-packages --skip-docker-ubuntu
    - run:
        name: Copy build tar/zip archives
        command: |
          mkdir -p build/kibana-docker/default-ubi8
          cp /home/circleci/project/target/kibana-8.2.4-SNAPSHOT-linux-x86_64.tar.gz build/kibana-docker/default-ubi8
          # ls build/kibana-docker/default-ubi8/

    - save_cache:
        paths: [build/kibana-docker]
        key: kibana-build
  
  build_and_push_image:
    docker:
       - image: cimg/aws:2023.12
    steps:
      # - checkout
      # activate docker
      - setup_remote_docker
      - restore_cache:
          keys: [kibana-build]
      - run:
          name: Build custom image
          command: |
            cd build/kibana-docker/default-ubi8
            docker build -t 243606292720.dkr.ecr.eu-west-1.amazonaws.com/cst-kibana:latest .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
      - run:
          name: AWS ECR login
          command: |
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 243606292720.dkr.ecr.eu-west-1.amazonaws.com
            # aws ecr describe-repositories --repository-name cst-kibana
      - run:
          name: Push image to AWS ECR
          command: |
            docker push 243606292720.dkr.ecr.eu-west-1.amazonaws.com/cst-kibana:latest
  
  # pull_case_enrichment:
  #   docker:
  #     - image: cimg/base:current
  #   steps:
  #     - checkout
  #     - run:
  #         name: 'checkout case enrichment'
  #         command: |
  #           cd plugins
  #           git clone git@github.com:CST-Dev-Analytics/nia-case-enrichment-kibana-plugin.git
  #           cd nia-case-enrichment-kibana-plugin
  #           yarn kbn bootstrap
  #           yarn plugin-helpers build  
            

# Define workflows
workflows:
  version: 2
  build_and_push:
    jobs:
      - build_plugin:
          filters:
            branches:
                only:
                  - feat/clone-case-enrichment #testing purpose
      - push_plugin_image:
          requires:
            - build_plugin

      - install_and_build:
          filters:
            branches:
                only:
                  - main-cst
      - build_and_push_image:
          requires:
            - install_and_build
          filters:
           branches:
              only:
                - main-cst