version: 2.1
jobs:
  build_and_push_image:
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      # Install nvm and yarn
      - run:
          name: Install nvm and yarn
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            . ~/.nvm/nvm.sh
            nvm install
            npm install -g yarn

      # Bootstrap the project
      - run:
          name: Bootstrap project
          command: yarn kbn bootstrap

      # Build project distributables
      - run:
          name: Build project distributables
          command: yarn build --docker-images --skip-os-packages --skip-docker-ubuntu

      # Copy build tar/zip archives
      - run:
          name: Copy build tar/zip archives
          command: |
            mkdir -p build/kibana-docker/default-ubi8
            cp target/kibana-8.2.4-SNAPSHOT-linux-x86_64.tar.gz build/kibana-docker/default-ubi8

      # Build custom image
      - run:
          name: Build custom image
          command: |
            docker build -t 243606292720.dkr.ecr.eu-west-1.amazonaws.com/cst-kibana:latest .

      # AWS ECR login
      - run:
          name: AWS ECR login
          command: |
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 243606292720.dkr.ecr.eu-west-1.amazonaws.com

      # Push image to AWS ECR
      - run:
          name: Push image to AWS ECR
          command: |
            docker push 243606292720.dkr.ecr.eu-west-1.amazonaws.com/cst-kibana:latest

# Define workflows
workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_image
