---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "localhost"

# Elasticsearch Connection
elasticsearch.hosts: [ "https://localhost:9200" ]
# elasticsearch.hosts: [ "https://dev.cstanalytics.com:9200" ]

# SSL settings
server.ssl.enabled: true
server.ssl.certificate: /Users/oluwatobisholanke/Desktop/cst/kibana/secrets/certs/kibana/kibana.crt
server.ssl.key: /Users/oluwatobisholanke/Desktop/cst/kibana/secrets/certs/kibana/kibana.key
server.ssl.certificateAuthorities: [ "/Users/oluwatobisholanke/Desktop/cst/kibana/secrets/certs/ca/ca.crt" ]
xpack.security.encryptionKey: C1tHnfrlfxSPxPlQ8BlgPB5qMNRtg5V5
xpack.encryptedSavedObjects.encryptionKey: D12GTfrlfxSPxPlGRBlgPB5qM5GOPDV5
xpack.reporting.encryptionKey: RSCueeHKzrqzOVTJhkjt17EMnzM96LlN

## X-Pack security credentials
elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2RlZmF1bHQ6d0xZaE1tUHpUbEMwbUVUQTVpM1Vmdw"
elasticsearch.ssl.certificateAuthorities: [ "/Users/oluwatobisholanke/Desktop/cst/kibana/secrets/certs/ca/ca.crt" ]

# =====================================================
# Your 'elastic' user password is: 7zO0pX01hm8
# Your Kibana Service Token is: AAEAAWVsYXN0aWMva2liYW5hL2RlZmF1bHQ6d0xZaE1tUHpUbEMwbUVUQTVpM1Vmdw
# =====================================================

## Reporting
xpack.screenshotting.browser.chromium.disableSandbox: true
xpack.reporting.queue.timeout: 600000

## Misc
elasticsearch.requestTimeout: 90000

## auditing log
xpack.security.audit.enabled: true
xpack.security.audit.appender:
  type: rolling-file
  fileName: ./logs/audit.log
  policy:
    type: time-interval
    interval: 1m
  strategy:
    type: numeric
    max: 100
  layout:
    type: json



## ElastAlert Plugin
#elastalert-kibana-plugin.serverHost: elastalert
#elastalert-kibana-plugin.serverPort: 3030